server:
  port: 9005
spring:
  application:
    name: search
  elasticsearch:
    rest:
      uris: http://192.168.188.129:9200
  main:
    allow-bean-definition-overriding: true

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka

feign:
  hystrix:
    enabled: true
  client:
    default:
      connectTimeout: 10000 #连接超时配置
      readTimeout: 60000 #执行超时配置

hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 10000