server:
  port: 9101
spring:
  application:
    name: search-web
  thymeleaf:
    cache: false

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka

feign:
  hystrix:
    enabled: true
  client:
    default:
      connectTimeout: 10000 #连接超时配置
      readTimeout: 60000 #执行超时配置

hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 10000

logging:
  level:
    com.offcn: debug