server:
  port: 9101
spring:
  application:
    name: weibo-auth
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
  #自定义配置
auth:
  clientId: client1  #客户端账号
  clientSecret: 123 #客户端密码
  redirectUri: http://localhost:9001/login.html
